#!/usr/bin/env python3
"""
ai_render.py — All-AI Document Renderer for Declassified Cases V9

Renders ALL documents using Claude Sonnet via LiteLLM proxy.
No templates. No Handlebars. Each document gets a unique, professionally
designed HTML page generated by Claude, then rendered to PDF via Chromium.

Usage: python3 ai_render.py <case_dir> [--model MODEL] [--skip-pdf] [--doc DOC_ID]

Requires:
  - LiteLLM proxy running on http://127.0.0.1:4000
  - Chromium installed for PDF rendering
  - cases/config/design_system.json
  - cases/config/doc_type_catalog.json
"""

import json
import sys
import os
import re
import base64
import subprocess
import argparse
from datetime import datetime
from pathlib import Path
from io import BytesIO

# Try to import PIL for image resizing
try:
    from PIL import Image
    HAS_PIL = True
except ImportError:
    HAS_PIL = False

# Try to import requests
try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False
    import urllib.request
    import urllib.error


# ═══════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════

LITELLM_URL = os.environ.get('LITELLM_URL', 'http://127.0.0.1:4000')
LITELLM_KEY = os.environ.get('LITELLM_API_KEY', 'local-litellm-key')
DEFAULT_MODEL = 'claude-sonnet-4-6'
MAX_IMAGE_WIDTH = 600  # Resize images to this max width (saves tokens)
MAX_PORTRAIT_WIDTH = 300  # Smaller for POI portraits
MAX_TOKENS = 32000  # Max output tokens per document
# ═══════════════════════════════════════════════════════
# Document tier classification
# ═══════════════════════════════════════════════════════

# Tier 1: Text-heavy docs — minimal prompt, cheap
TIER1_TYPES = {
    'interrogation_transcript',
    'official_memo',
    'court_order',
    'witness_statement',
    'transcript_911',
    'lab_report',
}

# Tier 2: Visual docs — full design prompt
# Everything else, including custom types

# Only POI portrait images get embedded (resized tiny)
# All other "images" are created by Claude in HTML/CSS
POI_IMAGE_MAX_WIDTH = 100  # ~5KB JPEG q70 = ~1.3K tokens (15x cheaper than 200px PNG)



# ═══════════════════════════════════════════════════════
# Utilities
# ═══════════════════════════════════════════════════════

def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def read_file(path):
    if path.exists():
        return path.read_text(encoding='utf-8')
    return ''


def find_workspace():
    """Find the workspace root (has cases/config/)."""
    candidates = [
        Path.home() / '.openclaw' / 'workspace-declassified',
        Path.home() / '.openclaw' / 'workspace',
        Path(__file__).parent.parent.parent,  # Relative to scripts/
    ]
    for c in candidates:
        if (c / 'cases' / 'config').exists():
            return c
    return None


def resize_image_to_base64(image_path, max_width=600):
    """Resize an image and return base64 data URI."""
    path = Path(image_path)
    if not path.exists():
        return None

    ext = path.suffix.lower().lstrip('.')
    if ext == 'jpg':
        ext = 'jpeg'
    mime = f'image/{ext}'

    if HAS_PIL:
        img = Image.open(path)
        if img.width > max_width:
            ratio = max_width / img.width
            new_size = (max_width, int(img.height * ratio))
            img = img.resize(new_size, Image.LANCZOS)
        buf = BytesIO()
        # Force JPEG output for smaller base64 size (TL-02: 15x cost reduction)
        if img.mode == 'RGBA':
            img = img.convert('RGB')
        img.save(buf, format='JPEG', quality=70)
        data = base64.b64encode(buf.getvalue()).decode()
        mime = 'image/jpeg'
    else:
        # No PIL — just encode at original size
        with open(path, 'rb') as f:
            data = base64.b64encode(f.read()).decode()

    return f'data:{mime};base64,{data}'


def call_litellm(model, system_prompt, user_prompt, max_tokens=MAX_TOKENS):
    """Call Anthropic API with streaming via curl (fixes WSL connection drops)."""
    api_key = os.environ.get('ANTHROPIC_API_KEY', '')
    if not api_key:
        raise ValueError('ANTHROPIC_API_KEY not set in environment')

    payload = json.dumps({
        'model': model,
        'max_tokens': max_tokens,
        'stream': True,
        'system': system_prompt,
        'messages': [{'role': 'user', 'content': user_prompt}]
    }, ensure_ascii=True)

    import tempfile
    with tempfile.NamedTemporaryFile(mode='wb', suffix='.json', delete=False) as f:
        f.write(payload.encode('utf-8'))
        tmp_path = f.name

    try:
        result = subprocess.run([
            'curl', '-s', '-S', '-N', '--max-time', '600',
            'https://api.anthropic.com/v1/messages',
            '-H', f'x-api-key: {api_key}',
            '-H', 'anthropic-version: 2023-06-01',
            '-H', 'content-type: application/json',
            '--data-binary', f'@{tmp_path}'
        ], capture_output=True, text=True, timeout=650)

        if result.returncode != 0:
            raise Exception(f'curl failed (rc={result.returncode}): {result.stderr[:200]}')

        if not result.stdout.strip():
            raise Exception(f'Empty response. stderr: {result.stderr[:200]}')

        # Parse SSE stream
        full_text = ''
        input_tokens = 0
        output_tokens = 0
        for line in result.stdout.split('\n'):
            if line.startswith('data: '):
                try:
                    event = json.loads(line[6:])
                    etype = event.get('type', '')
                    if etype == 'content_block_delta':
                        delta = event.get('delta', {})
                        if delta.get('type') == 'text_delta':
                            full_text += delta.get('text', '')
                    elif etype == 'message_delta':
                        usage = event.get('usage', {})
                        output_tokens = usage.get('output_tokens', output_tokens)
                    elif etype == 'message_start':
                        usage = event.get('message', {}).get('usage', {})
                        input_tokens = usage.get('input_tokens', 0)
                    elif etype == 'error':
                        err = event.get('error', {})
                        raise Exception(f'API error: {err.get("message", str(err))}')
                except json.JSONDecodeError:
                    pass

        if not full_text:
            raise Exception(f'No text in stream. Response starts: {result.stdout[:300]}')

        return full_text, {
            'input_tokens': input_tokens,
            'output_tokens': output_tokens,
            'total_tokens': input_tokens + output_tokens
        }
    finally:
        os.unlink(tmp_path)


def extract_html(text):
    """Extract HTML from Claude's response (may be wrapped in markdown fences)."""
    # Try to find HTML within code fences
    m = re.search(r'```html?\s*\n(.*?)```', text, re.DOTALL)
    if m:
        return m.group(1).strip()

    # Try to find <!DOCTYPE or <html or <style as start
    for marker in ['<!DOCTYPE', '<html', '<style', '<div']:
        idx = text.find(marker)
        if idx >= 0:
            return text[idx:].strip()

    # Return as-is (hopefully it's clean HTML)
    return text.strip()


def render_html_to_pdf(html_path, pdf_path, render_script):
    """Render HTML to PDF using Chromium."""
    try:
        result = subprocess.run(
            ['node', str(render_script), str(html_path), str(pdf_path)],
            capture_output=True, text=True, timeout=60
        )
        if result.returncode == 0 and Path(pdf_path).exists():
            size_kb = Path(pdf_path).stat().st_size / 1024
            return True, size_kb
        else:
            return False, result.stderr[:200]
    except Exception as e:
        return False, str(e)


# ═══════════════════════════════════════════════════════
# Image resolution
# ═══════════════════════════════════════════════════════

def resolve_images_for_doc(doc_id, art_briefs, case_dir):
    """Find ONLY POI portrait images for a document. All other visuals are created by Claude in HTML."""
    images = []
    for brief in art_briefs.get('briefs', []):
        if not isinstance(brief, dict):
            continue
        fn = brief.get('filename', '')
        is_poi = 'poi_' in fn.lower() or 'portrait' in fn.lower() or 'mugshot' in fn.lower()
        if not is_poi:
            continue

        # Check if this brief is for this document
        matches = False
        # Method 1: direct for_doc field
        if brief.get('for_doc') == doc_id:
            matches = True
        # Method 2: usage_map array (backwards compatibility)
        for usage in brief.get('usage_map', []):
            if usage.get('doc_id') == doc_id:
                matches = True
                break

        if not matches:
            continue

        poi = brief.get('for_poi', '')
        # Try paths: fn might already have visuals/canonical/ prefix
        search_paths = [
            case_dir / fn,
            case_dir / 'visuals' / 'canonical' / Path(fn).name,
        ]
        for sp in search_paths:
            if sp.exists():
                data_uri = resize_image_to_base64(sp, POI_IMAGE_MAX_WIDTH)
                if data_uri:
                    images.append({
                        'slot': brief.get('image_id', ''),
                        'purpose': f'POI portrait: {poi}',
                        'poi': poi,
                        'data_uri': data_uri,
                        'filename': fn,
                        'original_path': str(sp)
                    })
                break
    return images


# ═══════════════════════════════════════════════════════
# Prompt building
# ═══════════════════════════════════════════════════════

def build_system_prompt(design_system, doc_type_info, tier=2):
    """Build the system prompt for Claude. Tier 1 = minimal, Tier 2 = full design."""
    
    if tier == 1:
        # Tier 1: Short prompt for text-heavy documents
        return """You are a document designer for Declassified Cases, a physical detective mystery game.
Create a complete, self-contained HTML page that renders to PDF via Chromium.

RULES:
1. Output ONLY the HTML. Start with <!DOCTYPE html>, end with </html>.
2. ALL CSS in a <style> block. No external stylesheets.
3. @page { size: letter; margin: 12mm; } and body font-family serif or mono as appropriate.
4. PRINT RULES (CRITICAL):
   - Background MUST be white (#ffffff) or very light. NEVER use dark backgrounds (#000, #111, #1e1e1e, etc.)
   - All text must be dark on light background — these documents are PRINTED on paper.
   - No dark mode, no dark themes, no inverted colors.
   - If the document type suggests a digital screen (app, social media), still render it as a PRINTED SCREENSHOT on white paper with a border around the screen mockup.
5. If POI portrait images are provided as base64, embed them with <img src="...">.
6. ALL text must be HTML. Include case header at top, disclaimer footer at bottom.
7. No JavaScript. Print-friendly. Make it look like a real police/legal document.
8. Use appropriate styling: mono for transcripts, serif for legal docs, sans for forms.
9. Background MUST be white or light. These are PRINTED documents. NEVER use dark backgrounds.
10. Footer: 'Prepared for training / investigative simulation. All content is fictional.'"""
    
    # Tier 2: Full design prompt for visual documents
    return f"""You are a document designer for Declassified Cases, a physical detective mystery game sold as printed case file kits.

You create complete, self-contained HTML pages that render to PDF via headless Chromium.
You must CREATE all visual elements (diagrams, mockups, layouts, tables, charts) directly in HTML/CSS.
Do NOT expect pre-made images for anything except POI portraits.

DESIGN SYSTEM:
{json.dumps(design_system, indent=2)}

DOCUMENT TYPE DESIGN:
{json.dumps(doc_type_info, indent=2)}

CRITICAL RULES:
1. Output ONLY the complete HTML document. No explanation, no markdown fences.
2. Start with <!DOCTYPE html> and end with </html>
3. ALL CSS in a <style> block inside <head>. No external stylesheets.
4. POI portrait images are provided as base64 — use them in <img src="...">.
5. ALL other visuals (floor plans, phone mockups, evidence grids, charts) must be CREATED in HTML/CSS.
6. Page setup: @page {{ size: letter; margin: 12mm; }}
7. PRINT RULES (CRITICAL):
   - Background MUST be white (#ffffff) or very light. NEVER use dark backgrounds (#000, #111, #1e1e1e, etc.)
   - All text must be dark on light background — these documents are PRINTED on paper.
   - No dark mode, no dark themes, no inverted colors.
   - If the document type suggests a digital screen (app, social media), still render it as a PRINTED SCREENSHOT on white paper with a border around the screen mockup.
8. ALL text must be HTML text. Never rely on text inside images.
9. Include the evidence header (case number, doc ID, date) at top.
10. Include the training simulation disclaimer footer at bottom.
11. No JavaScript. Static HTML/CSS only.
12. Make it look like a REAL document of this type — authentic, immersive, detailed.
13. Use print-friendly CSS (printBackground: true in Chromium).
14. Background MUST be white or light. These are PRINTED documents. NEVER use dark backgrounds.
15. Each document should feel unique — vary details, effects, and micro-styling.

DETECTIVE ANNOTATIONS (if provided in the user prompt):
When the user prompt includes DETECTIVE ANNOTATIONS, render them as visual overlays:
- [margin_note] → Handwritten-style text in the margin, slightly rotated, using the handwritten font ('Caveat', cursive). Import: @import url('https://fonts.googleapis.com/css2?family=Caveat:wght@400;700');
- [sticky_note] → Yellow/pastel sticky note overlay, slightly rotated (CSS transform: rotate(-2deg to 3deg)), with handwritten font, positioned near the relevant content
- [highlight] → Yellow/orange semi-transparent highlight behind the relevant text (background-color with alpha)
- [underline] → Red or blue pen underline with slightly wavy effect
- [circled] → Red circle or oval drawn around content (CSS border-radius + border)
These annotations make the document feel like a real detective has been working on it. They are a CORE quality feature."""


def build_user_prompt(doc, content, case_info, images, experience_notes=''):
    """Build the user prompt for a specific document."""
    doc_id = doc.get('doc_id', '?')
    type_key = doc.get('type_key', 'unknown')
    envelope = doc.get('envelope', 'A')
    title = doc.get('in_world_title', '')
    timestamp = doc.get('timestamp', '')
    date = timestamp[:10] if timestamp else ''

    # Format images for the prompt
    image_section = ''
    if images:
        image_lines = []
        for i, img in enumerate(images, 1):
            purpose = img.get('purpose', 'document image')
            poi = img.get('poi', '')
            desc = f"Image {i}"
            if poi:
                desc += f" (POI: {poi})"
            desc += f": {purpose}"
            image_lines.append(f'{desc}')
            image_lines.append(f'<img src="{img["data_uri"]}" />')
        image_section = '\n'.join(image_lines)
    else:
        image_section = '(No images for this document — use text and layout only)'

    # Experience/emotional notes
    exp_section = ''
    if experience_notes:
        exp_section = f'\nEMOTIONAL BEAT / DETECTIVE NOTES:\n{experience_notes}\n'

    return f"""Design document {doc_id} (type: {type_key}) for this case.

CASE: {case_info.get('case_number', 'CASE-001')}
DOCUMENT ID: {doc_id}
ENVELOPE: {envelope}
TITLE: {title}
DATE: {date}

CONTENT (this is the narrative content — incorporate ALL of it into the document design):
---
{content}
---

IMAGES (embed these using the base64 data URIs provided):
{image_section}
{exp_section}
Generate the complete HTML document now. Start with <!DOCTYPE html>."""


# ═══════════════════════════════════════════════════════
# Main rendering pipeline
# ═══════════════════════════════════════════════════════

def render_document(doc, case_dir, workspace, design_system, type_catalog,
                    art_briefs, case_info, experience, model, tracker=None):
    """Render a single document using Claude API."""
    doc_id = doc.get('doc_id', '?')
    type_key = doc.get('type_key', '')
    envelope = doc.get('envelope', 'A')

    # Read content
    content_path = case_dir / f'envelope_{envelope}' / f'{doc_id}_content.md'
    content = read_file(content_path)
    if not content:
        print(f'  SKIP {doc_id}: no content file')
        return False

    # Get type design info
    if type_key in type_catalog.get('types', {}):
        doc_type_info = type_catalog['types'][type_key]
    else:
        # Custom type — use design_hint from clue_catalog
        doc_type_info = {
            'feel': doc.get('design_hint', f'A {type_key.replace("_", " ")} document.'),
            'layout': 'Professional document layout appropriate for this type.',
            'typography': 'Appropriate fonts for this document type.',
            'special_elements': [],
            'page_estimate': '1-2 pages',
            'background': 'White',
            'is_custom': True
        }

    # Resolve images
    images = resolve_images_for_doc(doc_id, art_briefs, case_dir)

    # Get experience notes from document_experience_map
    exp_notes = ''
    if experience:
        doc_exp = experience.get('document_experience_map', {}).get(doc_id, {})
        if doc_exp:
            parts = []
            beat = doc_exp.get('emotional_beat', '')
            if beat:
                parts.append(f'EMOTIONAL BEAT: {beat}')
            annotations = doc_exp.get('detective_annotations', [])
            if annotations:
                parts.append('DETECTIVE ANNOTATIONS:')
                for ann in annotations:
                    parts.append(f'  [{ann.get("type")}] {ann.get("content")} (position: {ann.get("position")}, style: {ann.get("style_hint")})')
            immersion = doc_exp.get('immersion_elements', [])
            if immersion:
                parts.append(f'IMMERSION ELEMENTS: {", ".join(immersion)}')
            exp_notes = '\n'.join(parts)

    # Build prompts
    # Determine tier
    tier = 1 if type_key in TIER1_TYPES else 2
    system_prompt = build_system_prompt(design_system, doc_type_info, tier=tier)
    user_prompt = build_user_prompt(doc, content, case_info, images, exp_notes)

    # Call Claude
    print(f'  Rendering {doc_id} ({type_key})...', end=' ', flush=True)
    try:
        html_raw, usage = call_litellm(model, system_prompt, user_prompt)
    except Exception as e:
        print(f'API ERROR: {e}')
        return False

    # Extract clean HTML
    html = extract_html(html_raw)

    # Write HTML
    layout_dir = case_dir / 'layout_specs'
    layout_dir.mkdir(parents=True, exist_ok=True)
    html_path = layout_dir / f'{doc_id}.html'
    html_path.write_text(html, encoding='utf-8')

    # Log cost
    cost = 0
    if tracker:
        cost = tracker.log_render_call(
            doc_id, model,
            usage.get('input_tokens', 0),
            usage.get('output_tokens', 0)
        )

    # Render PDF
    render_script = workspace / 'cases' / 'render' / 'render_pdf_system_chromium.js'
    pdf_path = layout_dir / f'{doc_id}.pdf'

    if render_script.exists():
        success, result = render_html_to_pdf(html_path, pdf_path, render_script)
        if success:
            print(f'OK ({result:.0f}KB) ${cost:.3f}')
        else:
            print(f'PDF FAIL: {result}')
            # Try alternative: direct chromium call
            try:
                chromium = '/usr/bin/chromium-browser'
                if not os.path.exists(chromium):
                    chromium = 'chromium-browser'
                subprocess.run([
                    chromium, '--headless=new', '--no-sandbox',
                    '--disable-gpu', '--print-to-pdf=' + str(pdf_path),
                    '--no-pdf-header-footer',
                    str(html_path.resolve())
                ], capture_output=True, timeout=30)
                if pdf_path.exists():
                    print(f'  (fallback OK: {pdf_path.stat().st_size / 1024:.0f}KB)')
                    return True
            except Exception:
                pass
            return False
    else:
        print(f'WARN: render script not found, HTML only')

    return True


def merge_envelope(case_dir, workspace, envelope, doc_ids):
    """Merge individual PDFs into envelope PDF."""
    merge_script = workspace / 'cases' / 'render' / 'merge_pdfs.js'
    final_dir = case_dir / 'final'
    final_dir.mkdir(parents=True, exist_ok=True)

    out_path = final_dir / f'Envelope_{envelope}.pdf'
    layout_dir = case_dir / 'layout_specs'

    pdf_paths = []
    for did in sorted(doc_ids):
        pdf = layout_dir / f'{did}.pdf'
        if pdf.exists() and pdf.stat().st_size > 500:
            pdf_paths.append(str(pdf))
        else:
            print(f'  WARN: {did}.pdf missing or empty')

    if not pdf_paths:
        print(f'  SKIP Envelope_{envelope}: no PDFs')
        return False

    try:
        args = ['node', str(merge_script), str(out_path)] + pdf_paths
        result = subprocess.run(args, capture_output=True, text=True, timeout=60)
        if result.returncode == 0 and out_path.exists():
            size_mb = out_path.stat().st_size / (1024 * 1024)
            print(f'  ✓ Envelope_{envelope}.pdf ({len(pdf_paths)} docs, {size_mb:.1f}MB)')
            return True
        else:
            print(f'  ✗ Envelope_{envelope}: {result.stderr[:200]}')
            return False
    except Exception as e:
        print(f'  ✗ Envelope_{envelope}: {e}')
        return False


def main():
    parser = argparse.ArgumentParser(description='AI Document Renderer V9')
    parser.add_argument('case_dir', help='Path to case export directory')
    parser.add_argument('--model', default=DEFAULT_MODEL,
                        help=f'LLM model for rendering (default: {DEFAULT_MODEL})')
    parser.add_argument('--skip-pdf', action='store_true',
                        help='Generate HTML only, skip PDF rendering')
    parser.add_argument('--doc', help='Render only this doc_id (e.g. A1)')
    parser.add_argument('--skip-merge', action='store_true',
                        help='Skip envelope merging')
    args = parser.parse_args()

    case_dir = Path(args.case_dir)
    workspace = find_workspace()

    if not workspace:
        print("ERROR: Cannot find workspace with cases/config/")
        sys.exit(1)

    config_dir = workspace / 'cases' / 'config'

    print(f'AI Document Renderer V9')
    print(f'Workspace: {workspace}')
    print(f'Case: {case_dir}')
    print(f'Model: {args.model}')
    print()

    # Load configs
    design_system = load_json(config_dir / 'design_system.json')
    type_catalog = load_json(config_dir / 'doc_type_catalog.json')
    catalog = load_json(case_dir / 'clue_catalog.json')
    plan = load_json(case_dir / 'case-plan.json')
    art_briefs = load_json(case_dir / 'art_briefs.json') if (case_dir / 'art_briefs.json').exists() else {'briefs': []}
    experience = load_json(case_dir / 'experience_design.json') if (case_dir / 'experience_design.json').exists() else {}

    # Build case info
    case_number = plan.get('case_number', plan.get('slug', 'CASE-001'))
    case_info = {
        'case_number': case_number,
        'title': plan.get('title', ''),
        'setting': plan.get('setting', {}),
    }

    # Initialize cost tracker
    sys.path.insert(0, str(workspace / 'cases' / 'scripts'))
    try:
        from cost_tracker import CostTracker
        tracker = CostTracker(case_dir)
    except ImportError:
        print("WARN: cost_tracker.py not found, costs will not be tracked")
        tracker = None

    # Collect documents
    documents = [d for d in catalog.get('documents', []) if isinstance(d, dict)]

    if args.doc:
        documents = [d for d in documents if d.get('doc_id') == args.doc]
        if not documents:
            print(f"ERROR: Document {args.doc} not found in clue_catalog")
            sys.exit(1)

    # Group by envelope
    envelopes = {}
    for doc in documents:
        env = doc.get('envelope', '?')
        if env not in envelopes:
            envelopes[env] = []
        envelopes[env].append(doc.get('doc_id', '?'))

    print(f'Documents: {len(documents)} total across {len(envelopes)} envelopes')
    print()

    # ── Render all documents ──
    print('═══ Rendering Documents ═══')
    success = 0
    errors = 0
    for doc in documents:
        ok = render_document(
            doc, case_dir, workspace, design_system, type_catalog,
            art_briefs, case_info, experience, args.model, tracker
        )
        if ok:
            success += 1
        else:
            errors += 1

    print()
    print(f'Rendered: {success} OK, {errors} errors')

    # ── Merge envelopes ──
    if not args.skip_merge and not args.skip_pdf:
        print()
        print('═══ Merging Envelopes ═══')
        for envelope, doc_ids in sorted(envelopes.items()):
            merge_envelope(case_dir, workspace, envelope, doc_ids)

    # ── Cost summary ──
    if tracker:
        print()
        print(tracker.get_summary())

    print()
    print('Done.')


if __name__ == '__main__':
    main()
